import type { ExerciseDef } from '../types'

/**
 * Hardcoded MVP exercise pool. Each exercise is tagged with the
 * environments it fits, a rough difficulty (1 easiest – 5 hardest), the
 * canonical movement it counts toward for progress tracking, and an
 * optional progression chain (group + level) the generator can use to
 * introduce a harder variation every few sessions.
 */
export const EXERCISE_POOL: ExerciseDef[] = [
  // ---------- PULL (bar required) ----------
  {
    id: 'dead-hang',
    name: 'Вис на турнике',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'seconds',
    difficulty: 1,
    description: 'Повисни на прямых руках, лопатки слегка сведены.',
    progressionGroup: 'pull-chain',
    progressionLevel: 1,
    variants: ['широкий хват', 'узкий хват', 'нейтральный хват'],
    tracks: 'pullUps',
  },
  {
    id: 'negative-pullups',
    name: 'Негативные подтягивания',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 2,
    description: 'Запрыгни в верхнюю точку, опускайся максимально медленно.',
    progressionGroup: 'pull-chain',
    progressionLevel: 2,
    variants: ['темп 5 сек', 'темп 8 сек'],
    tracks: 'pullUps',
  },
  {
    id: 'band-pullups',
    name: 'Подтягивания с резиной',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 2,
    description: 'Резина под колено или стопу снимает часть веса.',
    progressionGroup: 'pull-chain',
    progressionLevel: 3,
    tracks: 'pullUps',
  },
  {
    id: 'partial-pullups',
    name: 'Подтягивания в неполную амплитуду',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 3,
    description: 'Работай в верхней трети амплитуды, без выхода в дед-хэнг.',
    progressionGroup: 'pull-chain',
    progressionLevel: 4,
    tracks: 'pullUps',
  },
  {
    id: 'pullups-pronated',
    name: 'Подтягивания прямым хватом',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 3,
    description: 'Хват чуть шире плеч, ладони от себя.',
    progressionGroup: 'pull-chain',
    progressionLevel: 5,
    variants: ['средний хват', 'широкий хват'],
    tracks: 'pullUps',
  },
  {
    id: 'pullups-supinated',
    name: 'Подтягивания обратным хватом',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 3,
    description: 'Ладони к себе, хват на ширине плеч.',
    progressionGroup: 'pull-chain',
    progressionLevel: 5,
    tracks: 'pullUps',
  },
  {
    id: 'pullups-wide',
    name: 'Подтягивания широким хватом',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 4,
    description: 'Хват значительно шире плеч, амплитуда чуть короче.',
    progressionGroup: 'pull-chain',
    progressionLevel: 6,
    tracks: 'pullUps',
  },
  {
    id: 'commando-pullups',
    name: 'Коммандо подтягивания',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 4,
    description: 'Хват одной рукой перед собой, другой — за перекладиной, чередуй стороны.',
    progressionGroup: 'pull-chain',
    progressionLevel: 6,
    tracks: 'pullUps',
  },
  {
    id: 'archer-pullups',
    name: 'Архер подтягивания',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 5,
    description: 'Тянись к одной руке, вторая остаётся почти прямой.',
    progressionGroup: 'pull-chain',
    progressionLevel: 7,
    tracks: 'pullUps',
  },
  {
    id: 'towel-row',
    name: 'Тяга полотенцем в дверном проёме',
    environments: ['home-no-bar', 'no-equipment'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 2,
    description: 'Зацепи полотенце за ручку двери, тяни корпус к рукам, ноги упёрты в пол.',
    tracks: 'other',
  },
  {
    id: 'table-row',
    name: 'Тяга под столом',
    environments: ['home-no-bar'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 2,
    description: 'Ляг под устойчивый стол, тяни корпус к столешнице.',
    tracks: 'other',
  },

  // ---------- PUSH ----------
  {
    id: 'wall-pushups',
    name: 'Отжимания от стены',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 1,
    description: 'Руки на стене чуть шире плеч, корпус прямой.',
    progressionGroup: 'push-chain',
    progressionLevel: 1,
    tracks: 'pushUps',
  },
  {
    id: 'incline-pushups',
    name: 'Отжимания с возвышения',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 2,
    description: 'Руки на скамье, столе или парковой лавке.',
    progressionGroup: 'push-chain',
    progressionLevel: 2,
    tracks: 'pushUps',
  },
  {
    id: 'knee-pushups',
    name: 'Отжимания с колен',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 2,
    description: 'Колени на полу, корпус от колен до головы — прямая линия.',
    progressionGroup: 'push-chain',
    progressionLevel: 2,
    tracks: 'pushUps',
  },
  {
    id: 'full-pushups',
    name: 'Классические отжимания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 3,
    description: 'Ладони под плечами, таз не проваливать.',
    progressionGroup: 'push-chain',
    progressionLevel: 3,
    variants: ['широкая постановка рук', 'узкая постановка рук', 'пальцы внутрь'],
    tracks: 'pushUps',
  },
  {
    id: 'tempo-pushups',
    name: 'Отжимания с паузой внизу',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 3,
    description: 'Задержка 2 секунды в нижней точке на каждом повторе.',
    progressionGroup: 'push-chain',
    progressionLevel: 3,
    tracks: 'pushUps',
  },
  {
    id: 'pike-pushups',
    name: 'Пайк-отжимания (плечи)',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 4,
    description: 'Таз высоко вверх, макушкой тянись к полу между руками.',
    progressionGroup: 'push-chain',
    progressionLevel: 4,
    tracks: 'pushUps',
  },
  {
    id: 'diamond-pushups',
    name: 'Алмазные отжимания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 4,
    description: 'Ладони под грудью образуют ромб, локти близко к корпусу.',
    progressionGroup: 'push-chain',
    progressionLevel: 4,
    tracks: 'pushUps',
  },
  {
    id: 'archer-pushups',
    name: 'Архер отжимания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 5,
    description: 'Смещай вес на одну руку, вторая почти прямая в стороне.',
    progressionGroup: 'push-chain',
    progressionLevel: 5,
    tracks: 'pushUps',
  },
  {
    id: 'clap-pushups',
    name: 'Взрывные отжимания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 5,
    description: 'Оттолкнись от пола так, чтобы руки на мгновение оторвались.',
    progressionGroup: 'push-chain',
    progressionLevel: 5,
    tracks: 'pushUps',
  },

  // ---------- DIPS ----------
  {
    id: 'bench-dips',
    name: 'Обратные отжимания от скамьи',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 2,
    description: 'Руки на скамье или стуле за спиной, сгибай локти назад.',
    progressionGroup: 'dip-chain',
    progressionLevel: 1,
    tracks: 'dips',
  },
  {
    id: 'negative-dips',
    name: 'Негативные отжимания на брусьях',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 3,
    description: 'Из верхней точки медленно опускайся вниз.',
    progressionGroup: 'dip-chain',
    progressionLevel: 2,
    tracks: 'dips',
  },
  {
    id: 'partial-dips',
    name: 'Отжимания на брусьях в неполную амплитуду',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 3,
    description: 'Опускайся до половины и возвращайся наверх.',
    progressionGroup: 'dip-chain',
    progressionLevel: 3,
    tracks: 'dips',
  },
  {
    id: 'full-dips',
    name: 'Отжимания на брусьях',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 4,
    description: 'Полная амплитуда, плечи ниже локтей внизу.',
    progressionGroup: 'dip-chain',
    progressionLevel: 4,
    variants: ['корпус вертикально', 'корпус с наклоном вперёд'],
    tracks: 'dips',
  },

  // ---------- LEGS / SQUATS ----------
  {
    id: 'assisted-squats',
    name: 'Приседания с опорой',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 1,
    description: 'Держись руками за опору, приседай до параллели бёдер с полом.',
    progressionGroup: 'squat-chain',
    progressionLevel: 1,
    tracks: 'squats',
  },
  {
    id: 'bodyweight-squats',
    name: 'Приседания с весом тела',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 2,
    description: 'Стопы на ширине плеч, колени по направлению носков.',
    progressionGroup: 'squat-chain',
    progressionLevel: 2,
    variants: ['темп 3-1-3', 'пульс внизу', 'сумо-стойка'],
    tracks: 'squats',
  },
  {
    id: 'lunges',
    name: 'Выпады',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 2,
    description: 'Шаг вперёд, колено сзади почти касается пола.',
    progressionGroup: 'squat-chain',
    progressionLevel: 2,
    tracks: 'squats',
  },
  {
    id: 'bulgarian-split-squats',
    name: 'Болгарские сплит-приседания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 3,
    description: 'Задняя нога на возвышении, приседай на передней ноге.',
    progressionGroup: 'squat-chain',
    progressionLevel: 3,
    tracks: 'squats',
  },
  {
    id: 'assisted-pistol',
    name: 'Пистолетик с опорой',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 4,
    description: 'Держись за опору одной рукой, приседай на одной ноге.',
    progressionGroup: 'squat-chain',
    progressionLevel: 4,
    tracks: 'squats',
  },
  {
    id: 'pistol-squat',
    name: 'Пистолетик без опоры',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 5,
    description: 'Полное приседание на одной ноге, вторая вытянута вперёд.',
    progressionGroup: 'squat-chain',
    progressionLevel: 5,
    tracks: 'squats',
  },
  {
    id: 'jump-squats',
    name: 'Приседания с выпрыгиванием',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 4,
    description: 'Из приседа выпрыгни вверх, мягко приземлись.',
    tracks: 'other',
  },
  {
    id: 'wall-sit',
    name: 'Стульчик у стены',
    environments: ['home-no-bar', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'seconds',
    difficulty: 2,
    description: 'Спина прижата к стене, бёдра параллельны полу.',
    tracks: 'other',
  },

  // ---------- CORE ----------
  {
    id: 'knee-plank',
    name: 'Планка с колен',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'seconds',
    difficulty: 1,
    description: 'Предплечья и колени на полу, корпус прямой.',
    progressionGroup: 'core-chain',
    progressionLevel: 1,
    tracks: 'plank',
  },
  {
    id: 'plank',
    name: 'Планка',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'seconds',
    difficulty: 2,
    description: 'Предплечья и носки на полу, таз не провисает.',
    progressionGroup: 'core-chain',
    progressionLevel: 2,
    tracks: 'plank',
  },
  {
    id: 'side-plank',
    name: 'Боковая планка',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'seconds',
    difficulty: 3,
    description: 'Упор на одно предплечье, корпус боком, бёдра приподняты.',
    progressionGroup: 'core-chain',
    progressionLevel: 3,
    tracks: 'plank',
  },
  {
    id: 'hollow-body-hold',
    name: 'Холлоу-холд',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'seconds',
    difficulty: 3,
    description: 'Лёжа на спине, руки и ноги приподняты, поясница прижата к полу.',
    progressionGroup: 'core-chain',
    progressionLevel: 3,
    tracks: 'plank',
  },
  {
    id: 'hanging-knee-raises',
    name: 'Подъём коленей в висе',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 3,
    description: 'Вис на турнике, подтягивай колени к груди без раскачки.',
    progressionGroup: 'core-chain',
    progressionLevel: 4,
    tracks: 'other',
  },
  {
    id: 'hanging-leg-raises',
    name: 'Подъём прямых ног в висе',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 4,
    description: 'Вис на турнике, поднимай прямые ноги до параллели с полом.',
    progressionGroup: 'core-chain',
    progressionLevel: 5,
    tracks: 'other',
  },
  {
    id: 'l-sit-hang',
    name: 'Уголок в висе',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'core',
    unit: 'seconds',
    difficulty: 5,
    description: 'Вис на турнике, ноги удерживаются параллельно полу.',
    progressionGroup: 'core-chain',
    progressionLevel: 6,
    tracks: 'other',
  },
  {
    id: 'mountain-climbers',
    name: 'Скалолаз',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 3,
    description: 'Упор лёжа, поочерёдно подтягивай колени к груди в быстром темпе.',
    tracks: 'other',
  },
  {
    id: 'bicycle-crunches',
    name: 'Велосипед',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 2,
    description: 'Лёжа на спине, тянись локтем к противоположному колену.',
    tracks: 'other',
  },
  {
    id: 'superman',
    name: 'Супермен',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'seconds',
    difficulty: 2,
    description: 'Лёжа на животе, одновременно приподними руки, грудь и ноги.',
    tracks: 'other',
  },

  // ---------- FULL BODY ----------
  {
    id: 'burpees',
    name: 'Бёрпи',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'full-body',
    unit: 'reps',
    difficulty: 4,
    description: 'Присед — упор лёжа — отжимание — прыжок вверх.',
    tracks: 'other',
  },
  {
    id: 'glute-bridge',
    name: 'Ягодичный мостик',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 1,
    description: 'Лёжа на спине, поднимай таз, сжимая ягодицы вверху.',
    tracks: 'other',
  },
]

export function getExercisesForEnvironment(
  environment: ExerciseDef['environments'][number],
): ExerciseDef[] {
  return EXERCISE_POOL.filter((ex) => ex.environments.includes(environment))
}

export function getExerciseById(id: string): ExerciseDef | undefined {
  return EXERCISE_POOL.find((ex) => ex.id === id)
}
