import type { ExerciseDef } from '../types'

/**
 * Hardcoded MVP exercise pool. Each exercise is tagged with the
 * environments it fits, a rough difficulty (1 easiest – 5 hardest), the
 * canonical movement it counts toward for progress tracking, and an
 * optional progression chain (group + level) the generator can use to
 * introduce a harder variation every few sessions.
 */
export const EXERCISE_POOL: ExerciseDef[] = [
  // ---------- PULL (bar required) ----------
  {
    id: 'dead-hang',
    name: 'Вис на турнике',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'seconds',
    difficulty: 1,
    description: 'Повисни на прямых руках, лопатки слегка сведены.',
    progressionGroup: 'pull-chain',
    progressionLevel: 1,
    variants: ['широкий хват', 'узкий хват', 'нейтральный хват'],
    tracks: 'pullUps',
  },
  {
    id: 'negative-pullups',
    name: 'Негативные подтягивания',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 2,
    description: 'Запрыгни в верхнюю точку, опускайся максимально медленно.',
    progressionGroup: 'pull-chain',
    progressionLevel: 2,
    variants: ['темп 5 сек', 'темп 8 сек'],
    tracks: 'pullUps',
  },
  {
    id: 'band-pullups',
    name: 'Подтягивания с резиной',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 2,
    description: 'Резина под колено или стопу снимает часть веса.',
    progressionGroup: 'pull-chain',
    progressionLevel: 3,
    tracks: 'pullUps',
  },
  {
    id: 'partial-pullups',
    name: 'Подтягивания в неполную амплитуду',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 3,
    description: 'Работай в верхней трети амплитуды, без выхода в дед-хэнг.',
    progressionGroup: 'pull-chain',
    progressionLevel: 4,
    tracks: 'pullUps',
  },
  {
    id: 'pullups-pronated',
    name: 'Подтягивания прямым хватом',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 3,
    description: 'Хват чуть шире плеч, ладони от себя.',
    progressionGroup: 'pull-chain',
    progressionLevel: 5,
    variants: ['средний хват', 'широкий хват'],
    tracks: 'pullUps',
  },
  {
    id: 'pullups-supinated',
    name: 'Подтягивания обратным хватом',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 3,
    description: 'Ладони к себе, хват на ширине плеч.',
    progressionGroup: 'pull-chain',
    progressionLevel: 5,
    tracks: 'pullUps',
  },
  {
    id: 'pullups-wide',
    name: 'Подтягивания широким хватом',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 4,
    description: 'Хват значительно шире плеч, амплитуда чуть короче.',
    progressionGroup: 'pull-chain',
    progressionLevel: 6,
    tracks: 'pullUps',
  },
  {
    id: 'commando-pullups',
    name: 'Коммандо подтягивания',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 4,
    description: 'Хват одной рукой перед собой, другой — за перекладиной, чередуй стороны.',
    progressionGroup: 'pull-chain',
    progressionLevel: 6,
    tracks: 'pullUps',
  },
  {
    id: 'archer-pullups',
    name: 'Архер подтягивания',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 5,
    description: 'Тянись к одной руке, вторая остаётся почти прямой.',
    progressionGroup: 'pull-chain',
    progressionLevel: 7,
    tracks: 'pullUps',
  },
  {
    id: 'towel-row',
    name: 'Тяга полотенцем в дверном проёме',
    environments: ['home-no-bar', 'no-equipment'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 2,
    description: 'Зацепи полотенце за ручку двери, тяни корпус к рукам, ноги упёрты в пол.',
    tracks: 'other',
  },
  {
    id: 'table-row',
    name: 'Тяга под столом',
    environments: ['home-no-bar'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 2,
    description: 'Ляг под устойчивый стол, тяни корпус к столешнице.',
    tracks: 'other',
  },
  {
    id: 'scapular-pulls',
    name: 'Подтягивания лопаток в висе',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 1,
    description: 'Вис на прямых руках, сведи и разведи лопатки, не сгибая локти.',
    progressionGroup: 'pull-chain',
    progressionLevel: 1,
    tracks: 'pullUps',
  },
  {
    id: 'flexed-arm-hang',
    name: 'Удержание в верхней точке',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'seconds',
    difficulty: 3,
    description: 'Подтянись и замри подбородком над перекладиной как можно дольше.',
    progressionGroup: 'pull-chain',
    progressionLevel: 4,
    tracks: 'pullUps',
  },
  {
    id: 'close-grip-pullups',
    name: 'Подтягивания узким хватом',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 3,
    description: 'Хват на ширине ладони, ладони друг к другу на нейтральных ручках.',
    progressionGroup: 'pull-chain',
    progressionLevel: 5,
    tracks: 'pullUps',
  },
  {
    id: 'l-sit-pullups',
    name: 'Подтягивания с уголком',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 5,
    description: 'Подтягивания с удержанием прямых ног параллельно полу.',
    progressionGroup: 'pull-chain',
    progressionLevel: 7,
    tracks: 'pullUps',
  },
  {
    id: 'typewriter-pullups',
    name: 'Тайпрайтер подтягивания',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 5,
    description: 'Подтянись и веди подбородок вдоль перекладины от одной руки к другой.',
    progressionGroup: 'pull-chain',
    progressionLevel: 8,
    tracks: 'pullUps',
  },
  {
    id: 'one-arm-pullup-negative',
    name: 'Негатив подтягивания на одной руке',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 5,
    description: 'Одна рука на перекладине, вторая слегка страхует — опускайся медленно.',
    progressionGroup: 'pull-chain',
    progressionLevel: 9,
    tracks: 'pullUps',
  },
  {
    id: 'gravitron-pullups',
    name: 'Подтягивания в гравитроне',
    environments: ['gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 2,
    description: 'Тренажёр с противовесом снимает часть веса тела.',
    progressionGroup: 'pull-chain',
    progressionLevel: 3,
    tracks: 'pullUps',
  },
  {
    id: 'lat-pulldown',
    name: 'Тяга верхнего блока',
    environments: ['gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 2,
    description: 'Тяга рукояти к груди, локти идут вниз и назад.',
    tracks: 'other',
  },
  {
    id: 'seated-cable-row',
    name: 'Тяга нижнего блока сидя',
    environments: ['gym'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 2,
    description: 'Спина прямая, тяни рукоять к животу, сводя лопатки.',
    tracks: 'other',
  },
  {
    id: 'resistance-band-row',
    name: 'Тяга резинкой к поясу',
    environments: ['home-no-bar', 'home-bar'],
    muscleGroup: 'pull',
    unit: 'reps',
    difficulty: 2,
    description: 'Закрепи резину на двери, тяни рукояти к поясу, лопатки сведены.',
    tracks: 'other',
  },

  // ---------- PUSH ----------
  {
    id: 'wall-pushups',
    name: 'Отжимания от стены',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 1,
    description: 'Руки на стене чуть шире плеч, корпус прямой.',
    progressionGroup: 'push-chain',
    progressionLevel: 1,
    tracks: 'pushUps',
  },
  {
    id: 'incline-pushups',
    name: 'Отжимания с возвышения',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 2,
    description: 'Руки на скамье, столе или парковой лавке.',
    progressionGroup: 'push-chain',
    progressionLevel: 2,
    tracks: 'pushUps',
  },
  {
    id: 'knee-pushups',
    name: 'Отжимания с колен',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 2,
    description: 'Колени на полу, корпус от колен до головы — прямая линия.',
    progressionGroup: 'push-chain',
    progressionLevel: 2,
    tracks: 'pushUps',
  },
  {
    id: 'full-pushups',
    name: 'Классические отжимания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 3,
    description: 'Ладони под плечами, таз не проваливать.',
    progressionGroup: 'push-chain',
    progressionLevel: 3,
    variants: ['широкая постановка рук', 'узкая постановка рук', 'пальцы внутрь'],
    tracks: 'pushUps',
  },
  {
    id: 'tempo-pushups',
    name: 'Отжимания с паузой внизу',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 3,
    description: 'Задержка 2 секунды в нижней точке на каждом повторе.',
    progressionGroup: 'push-chain',
    progressionLevel: 3,
    tracks: 'pushUps',
  },
  {
    id: 'pike-pushups',
    name: 'Пайк-отжимания (плечи)',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 4,
    description: 'Таз высоко вверх, макушкой тянись к полу между руками.',
    progressionGroup: 'push-chain',
    progressionLevel: 4,
    tracks: 'pushUps',
  },
  {
    id: 'diamond-pushups',
    name: 'Алмазные отжимания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 4,
    description: 'Ладони под грудью образуют ромб, локти близко к корпусу.',
    progressionGroup: 'push-chain',
    progressionLevel: 4,
    tracks: 'pushUps',
  },
  {
    id: 'archer-pushups',
    name: 'Архер отжимания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 5,
    description: 'Смещай вес на одну руку, вторая почти прямая в стороне.',
    progressionGroup: 'push-chain',
    progressionLevel: 5,
    tracks: 'pushUps',
  },
  {
    id: 'clap-pushups',
    name: 'Взрывные отжимания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 5,
    description: 'Оттолкнись от пола так, чтобы руки на мгновение оторвались.',
    progressionGroup: 'push-chain',
    progressionLevel: 5,
    tracks: 'pushUps',
  },
  {
    id: 'explosive-knee-pushups',
    name: 'Взрывные отжимания с колен',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 2,
    description: 'Мягкий вход во взрывную силу: отжимания с колен с ускорением вверх.',
    progressionGroup: 'push-chain',
    progressionLevel: 2,
    tracks: 'pushUps',
  },
  {
    id: 'hindu-pushups',
    name: 'Хинду-отжимания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 3,
    description: "Из позы 'горка' плавно опустись вперёд-вниз и прогнись вверх.",
    progressionGroup: 'push-chain',
    progressionLevel: 3,
    tracks: 'pushUps',
  },
  {
    id: 'shoulder-taps',
    name: 'Касания плеч в упоре лёжа',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 2,
    description: 'Упор лёжа, поочерёдно касайся ладонью противоположного плеча, таз не качается.',
    tracks: 'other',
  },
  {
    id: 'decline-pushups',
    name: 'Отжимания ноги на возвышении',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 4,
    description: 'Ноги на скамье или ступеньке, руки на полу — акцент на верх груди и плечи.',
    progressionGroup: 'push-chain',
    progressionLevel: 4,
    tracks: 'pushUps',
  },
  {
    id: 'spiderman-pushups',
    name: 'Спайдермен отжимания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 4,
    description: 'В каждом повторе подтягивай колено к локтю с той же стороны.',
    progressionGroup: 'push-chain',
    progressionLevel: 4,
    tracks: 'pushUps',
  },
  {
    id: 'one-arm-pushup-assisted',
    name: 'Отжимание на одной руке с опорой',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 5,
    description: 'Одна рука за спиной, ноги широко для баланса, отжимайся на одной руке.',
    progressionGroup: 'push-chain',
    progressionLevel: 6,
    tracks: 'pushUps',
  },
  {
    id: 'planche-lean',
    name: 'Планш-наклон',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'seconds',
    difficulty: 5,
    description: 'Упор лёжа, наклонись плечами вперёд за линию ладоней и удерживай.',
    progressionGroup: 'push-chain',
    progressionLevel: 6,
    tracks: 'pushUps',
  },
  {
    id: 'typewriter-pushups',
    name: 'Тайпрайтер отжимания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 5,
    description: 'В нижней точке широких отжиманий переноси вес от одной руки к другой.',
    progressionGroup: 'push-chain',
    progressionLevel: 7,
    tracks: 'pushUps',
  },
  {
    id: 'chest-press-machine',
    name: 'Жим от груди в тренажёре',
    environments: ['gym'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 2,
    description: 'Спина прижата к спинке, толкай рукояти вперёд без рывка.',
    tracks: 'other',
  },
  {
    id: 'cable-chest-fly',
    name: 'Сведение рук в кроссовере',
    environments: ['gym'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 2,
    description: 'Сведи рукояти перед собой по дуге, локти слегка согнуты.',
    tracks: 'other',
  },

  // ---------- DIPS ----------
  {
    id: 'bench-dips',
    name: 'Обратные отжимания от скамьи',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 2,
    description: 'Руки на скамье или стуле за спиной, сгибай локти назад.',
    progressionGroup: 'dip-chain',
    progressionLevel: 1,
    tracks: 'dips',
  },
  {
    id: 'negative-dips',
    name: 'Негативные отжимания на брусьях',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 3,
    description: 'Из верхней точки медленно опускайся вниз.',
    progressionGroup: 'dip-chain',
    progressionLevel: 2,
    tracks: 'dips',
  },
  {
    id: 'partial-dips',
    name: 'Отжимания на брусьях в неполную амплитуду',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 3,
    description: 'Опускайся до половины и возвращайся наверх.',
    progressionGroup: 'dip-chain',
    progressionLevel: 3,
    tracks: 'dips',
  },
  {
    id: 'full-dips',
    name: 'Отжимания на брусьях',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 4,
    description: 'Полная амплитуда, плечи ниже локтей внизу.',
    progressionGroup: 'dip-chain',
    progressionLevel: 4,
    variants: ['корпус вертикально', 'корпус с наклоном вперёд'],
    tracks: 'dips',
  },
  {
    id: 'bench-dips-feet-elevated',
    name: 'Отжимания от скамьи, ноги на опоре',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 3,
    description: 'Ноги на второй опоре — сложнее классических отжиманий от скамьи.',
    progressionGroup: 'dip-chain',
    progressionLevel: 2,
    tracks: 'dips',
  },
  {
    id: 'straight-bar-support-hold',
    name: 'Упор на прямых руках на брусьях',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'push',
    unit: 'seconds',
    difficulty: 3,
    description: 'Замри в верхней точке на прямых руках, плечи опущены от ушей.',
    progressionGroup: 'dip-chain',
    progressionLevel: 3,
    tracks: 'dips',
  },
  {
    id: 'tempo-dips',
    name: 'Отжимания на брусьях с паузой',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 4,
    description: 'Задержка 2 секунды в нижней точке на каждом повторе.',
    progressionGroup: 'dip-chain',
    progressionLevel: 4,
    tracks: 'dips',
  },
  {
    id: 'single-bar-dips',
    name: 'Отжимания на одной перекладине',
    environments: ['home-bar'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 4,
    description: 'Одна перекладина, руки рядом, ноги скрещены сзади — брусья дома.',
    tracks: 'dips',
  },
  {
    id: 'korean-dips',
    name: 'Корейские отжимания на брусьях',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 5,
    description: 'Отжимания на одних брусьях с уходом корпуса далеко вперёд-вниз.',
    progressionGroup: 'dip-chain',
    progressionLevel: 5,
    tracks: 'dips',
  },
  {
    id: 'assisted-dip-machine',
    name: 'Отжимания на брусьях в гравитроне',
    environments: ['gym'],
    muscleGroup: 'push',
    unit: 'reps',
    difficulty: 2,
    description: 'Тренажёр-гравитрон снимает часть веса — выбери противовес по силам.',
    tracks: 'dips',
  },

  // ---------- LEGS / SQUATS ----------
  {
    id: 'assisted-squats',
    name: 'Приседания с опорой',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 1,
    description: 'Держись руками за опору, приседай до параллели бёдер с полом.',
    progressionGroup: 'squat-chain',
    progressionLevel: 1,
    tracks: 'squats',
  },
  {
    id: 'bodyweight-squats',
    name: 'Приседания с весом тела',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 2,
    description: 'Стопы на ширине плеч, колени по направлению носков.',
    progressionGroup: 'squat-chain',
    progressionLevel: 2,
    variants: ['темп 3-1-3', 'пульс внизу', 'сумо-стойка'],
    tracks: 'squats',
  },
  {
    id: 'lunges',
    name: 'Выпады',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 2,
    description: 'Шаг вперёд, колено сзади почти касается пола.',
    progressionGroup: 'squat-chain',
    progressionLevel: 2,
    tracks: 'squats',
  },
  {
    id: 'bulgarian-split-squats',
    name: 'Болгарские сплит-приседания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 3,
    description: 'Задняя нога на возвышении, приседай на передней ноге.',
    progressionGroup: 'squat-chain',
    progressionLevel: 3,
    tracks: 'squats',
  },
  {
    id: 'assisted-pistol',
    name: 'Пистолетик с опорой',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 4,
    description: 'Держись за опору одной рукой, приседай на одной ноге.',
    progressionGroup: 'squat-chain',
    progressionLevel: 4,
    tracks: 'squats',
  },
  {
    id: 'pistol-squat',
    name: 'Пистолетик без опоры',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 5,
    description: 'Полное приседание на одной ноге, вторая вытянута вперёд.',
    progressionGroup: 'squat-chain',
    progressionLevel: 5,
    tracks: 'squats',
  },
  {
    id: 'jump-squats',
    name: 'Приседания с выпрыгиванием',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 4,
    description: 'Из приседа выпрыгни вверх, мягко приземлись.',
    tracks: 'other',
  },
  {
    id: 'wall-sit',
    name: 'Стульчик у стены',
    environments: ['home-no-bar', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'seconds',
    difficulty: 2,
    description: 'Спина прижата к стене, бёдра параллельны полу.',
    tracks: 'other',
  },
  {
    id: 'calf-raises',
    name: 'Подъёмы на носки',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 1,
    description: 'Поднимайся на носки, задержись вверху на секунду.',
    tracks: 'other',
  },
  {
    id: 'single-leg-calf-raise',
    name: 'Подъём на носок одной ногой',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 3,
    description: 'Держись за опору, поднимайся на носок одной ноги.',
    tracks: 'other',
  },
  {
    id: 'step-ups',
    name: 'Зашагивания на возвышение',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 2,
    description: 'Шаг на скамью или ступеньку и обратно, меняй ногу.',
    progressionGroup: 'squat-chain',
    progressionLevel: 2,
    tracks: 'squats',
  },
  {
    id: 'sumo-squats',
    name: 'Сумо-приседания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 2,
    description: 'Широкая стойка, носки врозь, приседай глубоко.',
    progressionGroup: 'squat-chain',
    progressionLevel: 2,
    tracks: 'squats',
  },
  {
    id: 'cossack-squats',
    name: 'Казачьи приседания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 4,
    description: 'Широкая стойка, перенос веса на одну ногу, другая прямая в сторону.',
    progressionGroup: 'squat-chain',
    progressionLevel: 4,
    tracks: 'squats',
  },
  {
    id: 'pistol-squat-negative',
    name: 'Негатив пистолетика',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 4,
    description: 'Медленно опускайся в присед на одной ноге, вставай с помощью.',
    progressionGroup: 'squat-chain',
    progressionLevel: 5,
    tracks: 'squats',
  },
  {
    id: 'shrimp-squats',
    name: 'Приседания-креветка',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 5,
    description: 'Присед на одной ноге, вторая согнута сзади и придерживается рукой.',
    progressionGroup: 'squat-chain',
    progressionLevel: 6,
    tracks: 'squats',
  },
  {
    id: 'nordic-curl-negative',
    name: 'Негатив нордик-керла',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 5,
    description: 'Зафиксируй стопы, медленно наклоняйся вперёд, сдерживая бёдрами.',
    progressionGroup: 'squat-chain',
    progressionLevel: 7,
    tracks: 'squats',
  },
  {
    id: 'broad-jumps',
    name: 'Прыжки в длину с места',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 4,
    description: 'Прыжок вперёд с двух ног на максимальное расстояние, мягкое приземление.',
    tracks: 'other',
  },
  {
    id: 'leg-press-machine',
    name: 'Жим ногами в тренажёре',
    environments: ['gym'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 2,
    description: 'Стопы на ширине плеч, толкай платформу без резких рывков.',
    tracks: 'other',
  },
  {
    id: 'leg-extension-machine',
    name: 'Разгибание ног в тренажёре',
    environments: ['gym'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 2,
    description: 'Разгибай колени плавно, задержись вверху на секунду.',
    tracks: 'other',
  },
  {
    id: 'hamstring-curl-machine',
    name: 'Сгибание ног в тренажёре',
    environments: ['gym'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 2,
    description: 'Сгибай колени, подтягивая валик к бёдрам.',
    tracks: 'other',
  },

  // ---------- CORE ----------
  {
    id: 'knee-plank',
    name: 'Планка с колен',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'seconds',
    difficulty: 1,
    description: 'Предплечья и колени на полу, корпус прямой.',
    progressionGroup: 'core-chain',
    progressionLevel: 1,
    tracks: 'plank',
  },
  {
    id: 'plank',
    name: 'Планка',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'seconds',
    difficulty: 2,
    description: 'Предплечья и носки на полу, таз не провисает.',
    progressionGroup: 'core-chain',
    progressionLevel: 2,
    tracks: 'plank',
  },
  {
    id: 'side-plank',
    name: 'Боковая планка',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'seconds',
    difficulty: 3,
    description: 'Упор на одно предплечье, корпус боком, бёдра приподняты.',
    progressionGroup: 'core-chain',
    progressionLevel: 3,
    tracks: 'plank',
  },
  {
    id: 'hollow-body-hold',
    name: 'Холлоу-холд',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'seconds',
    difficulty: 3,
    description: 'Лёжа на спине, руки и ноги приподняты, поясница прижата к полу.',
    progressionGroup: 'core-chain',
    progressionLevel: 3,
    tracks: 'plank',
  },
  {
    id: 'hanging-knee-raises',
    name: 'Подъём коленей в висе',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 3,
    description: 'Вис на турнике, подтягивай колени к груди без раскачки.',
    progressionGroup: 'core-chain',
    progressionLevel: 4,
    tracks: 'other',
  },
  {
    id: 'hanging-leg-raises',
    name: 'Подъём прямых ног в висе',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 4,
    description: 'Вис на турнике, поднимай прямые ноги до параллели с полом.',
    progressionGroup: 'core-chain',
    progressionLevel: 5,
    tracks: 'other',
  },
  {
    id: 'l-sit-hang',
    name: 'Уголок в висе',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'core',
    unit: 'seconds',
    difficulty: 5,
    description: 'Вис на турнике, ноги удерживаются параллельно полу.',
    progressionGroup: 'core-chain',
    progressionLevel: 6,
    tracks: 'other',
  },
  {
    id: 'mountain-climbers',
    name: 'Скалолаз',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 3,
    description: 'Упор лёжа, поочерёдно подтягивай колени к груди в быстром темпе.',
    tracks: 'other',
  },
  {
    id: 'bicycle-crunches',
    name: 'Велосипед',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 2,
    description: 'Лёжа на спине, тянись локтем к противоположному колену.',
    tracks: 'other',
  },
  {
    id: 'superman',
    name: 'Супермен',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'seconds',
    difficulty: 2,
    description: 'Лёжа на животе, одновременно приподними руки, грудь и ноги.',
    tracks: 'other',
  },
  {
    id: 'dead-bug',
    name: 'Мёртвый жук',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 1,
    description: 'Лёжа на спине, поочерёдно опускай противоположные руку и ногу, поясница прижата.',
    progressionGroup: 'core-chain',
    progressionLevel: 1,
    tracks: 'plank',
  },
  {
    id: 'bird-dog',
    name: 'Птица-собака',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 1,
    description: 'На четвереньках вытягивай противоположные руку и ногу, удерживай баланс.',
    tracks: 'other',
  },
  {
    id: 'russian-twists',
    name: 'Русские скручивания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 2,
    description: 'Сидя с приподнятыми ногами, поворачивай корпус в стороны.',
    tracks: 'other',
  },
  {
    id: 'flutter-kicks',
    name: 'Ножницы ногами',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 2,
    description: 'Лёжа на спине, поясница прижата, чередуй махи прямыми ногами вверх-вниз.',
    tracks: 'other',
  },
  {
    id: 'reverse-crunches',
    name: 'Обратные скручивания',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 2,
    description: 'Лёжа на спине, подтягивай колени к груди, отрывая таз от пола.',
    tracks: 'other',
  },
  {
    id: 'v-ups',
    name: 'Складка',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 3,
    description: 'Одновременно поднимай прямые руки и ноги, тянись к носкам.',
    progressionGroup: 'core-chain',
    progressionLevel: 3,
    tracks: 'plank',
  },
  {
    id: 'plank-to-pike',
    name: 'Планка-горка',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 3,
    description: 'В планке подними таз вверх, образуя горку, и вернись.',
    tracks: 'other',
  },
  {
    id: 'side-plank-hip-dips',
    name: 'Боковая планка с касанием бедра',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 3,
    description: 'В боковой планке опускай и поднимай таз короткими движениями.',
    progressionGroup: 'core-chain',
    progressionLevel: 3,
    tracks: 'plank',
  },
  {
    id: 'windshield-wipers',
    name: 'Дворники в висе',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 5,
    description: 'Вис на турнике, прямые ноги вместе поворачивай из стороны в сторону.',
    tracks: 'other',
  },
  {
    id: 'dragon-flag-negative',
    name: 'Негатив флажка дракона',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 5,
    description: 'Держась руками за опору за головой, медленно опускай прямое тело вниз.',
    progressionGroup: 'core-chain',
    progressionLevel: 7,
    tracks: 'plank',
  },
  {
    id: 'front-lever-tuck',
    name: 'Группированный передний вис',
    environments: ['home-bar', 'park', 'gym'],
    muscleGroup: 'core',
    unit: 'seconds',
    difficulty: 5,
    description: 'Вис на турнике, подтяни колени к груди и отклони корпус горизонтально.',
    progressionGroup: 'core-chain',
    progressionLevel: 8,
    tracks: 'plank',
  },
  {
    id: 'ab-crunches-machine',
    name: 'Скручивания в тренажёре',
    environments: ['gym'],
    muscleGroup: 'core',
    unit: 'reps',
    difficulty: 2,
    description: 'Тренажёр для пресса, контролируй движение, не рви резко.',
    tracks: 'other',
  },

  // ---------- FULL BODY ----------
  {
    id: 'burpees',
    name: 'Бёрпи',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'full-body',
    unit: 'reps',
    difficulty: 4,
    description: 'Присед — упор лёжа — отжимание — прыжок вверх.',
    tracks: 'other',
  },
  {
    id: 'glute-bridge',
    name: 'Ягодичный мостик',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'legs',
    unit: 'reps',
    difficulty: 1,
    description: 'Лёжа на спине, поднимай таз, сжимая ягодицы вверху.',
    tracks: 'other',
  },
  {
    id: 'jumping-jacks',
    name: 'Прыжки звёздочкой',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'full-body',
    unit: 'reps',
    difficulty: 1,
    description: 'Прыжки с разведением рук и ног для разминки.',
    tracks: 'other',
  },
  {
    id: 'inchworm',
    name: 'Гусеница',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'full-body',
    unit: 'reps',
    difficulty: 2,
    description: 'Наклонись, дойди руками до упора лёжа и обратно к стопам.',
    tracks: 'other',
  },
  {
    id: 'squat-thrusts',
    name: 'Бёрпи без прыжка',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'full-body',
    unit: 'reps',
    difficulty: 3,
    description: 'Присед — упор лёжа — обратно в присед, без прыжка и отжимания.',
    tracks: 'other',
  },
  {
    id: 'bear-crawl',
    name: 'Медвежья походка',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'full-body',
    unit: 'reps',
    difficulty: 3,
    description: 'Передвижение на руках и стопах, колени чуть над полом.',
    tracks: 'other',
  },
  {
    id: 'crab-walk',
    name: 'Походка краба',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'full-body',
    unit: 'reps',
    difficulty: 3,
    description: 'Сядь, обопрись руками сзади, шагай вперёд-назад на руках и ногах.',
    tracks: 'other',
  },
  {
    id: 'mountain-climber-sprint',
    name: 'Скалолаз в темпе',
    environments: ['home-no-bar', 'home-bar', 'park', 'gym', 'no-equipment'],
    muscleGroup: 'full-body',
    unit: 'reps',
    difficulty: 4,
    description: 'Быстрый скалолаз в максимальном темпе 20–30 секунд.',
    tracks: 'other',
  },
]

export function getExercisesForEnvironment(
  environment: ExerciseDef['environments'][number],
): ExerciseDef[] {
  return EXERCISE_POOL.filter((ex) => ex.environments.includes(environment))
}

export function getExerciseById(id: string): ExerciseDef | undefined {
  return EXERCISE_POOL.find((ex) => ex.id === id)
}
